- Tensors
- Florent Dufour
- 2016 - 2022

In [1]:
# Numpy
import numpy as np
# Tensorflow
import tensorflow as tf

In [ ]:
print(np.version.full_version)
print(tf.version.VERSION) # Version 2.x.x !

1.19.5
2.7.0


# Tensors

> Generalisation of vectors and matrices to potentially higher dimensions. Internally, TensorFlow representstensors as n-dimensional arrays of base datatypes (TensorFlow Guide)
>> A Tensor is made of a datatype and shape (dimension of the tensor).
>>> Tensor represents a partialy defined computation that can create a value when we build the _graph_ in a _session._

Tensors can be:

- Variables (only mutable tensor)
- Constant
- Placeholder
- SparseTensor

In [ ]:
# Creating tensors
string = tf.Variable("I put a string here", tf.string)
entier = tf.Variable(66, tf.int16)
reel   = tf.Variable(3.14, tf.float64)

In [ ]:
# Rank (=degree) of tensors
rank0_tensor = tf.Variable("This is a string", tf.string) # Scalar
rank1_tensor = tf.Variable(["Lundi", "Mardi"], tf.string) # Vector
rank2_tensor = tf.Variable([["Lundi", "Mardi", "Mercredi"], ["Monday", "Tuesday", "Wednesday"]], tf.string) # Matrix

print("Rank 0:", tf.rank(rank0_tensor))
print("Rank 1:", tf.rank(rank1_tensor))
print("Rank 2:", tf.rank(rank2_tensor))

Rank 0: tf.Tensor(0, shape=(), dtype=int32)
Rank 1: tf.Tensor(1, shape=(), dtype=int32)
Rank 2: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
# Shape of tensors: amount o elements in each dimension
print("Shape rank 0:", rank0_tensor.shape)
print("Shape rank 1:", rank1_tensor.shape)
print("Shape rank 2:", rank2_tensor.shape)

# Change shape
tensor_123 = tf.ones([1, 2, 3])
print("Tensor 1,2,3: ", tensor_123) # 1 interior list, w/ 2 inside list. Each list contains 3 elements
tensor_231 = tf.reshape(tensor_123, [2, 3, 1])
print("Tensor 2,3,1: ", tensor_231) # 2 lists containing 3 list, each containing 1 element
tensor_3_1 = tf.reshape(tensor_231, [3, -1])
print("Tensor 3, -1: ", tensor_3_1) # -1 lets tf compute the size of the dimension. In this case, it will give [3,2]
tensor_6 = tf.reshape(tensor_123, [6])
print("Tensor 6: ", tensor_6) # Flatten the tensor

Shape rank 0: ()
Shape rank 1: (2,)
Shape rank 2: (2, 3)
Tensor 1,2,3:  tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
Tensor 2,3,1:  tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
Tensor 3, -1:  tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
Tensor 6:  tf.Tensor([1. 1. 1. 1. 1. 1.], shape=(6,), dtype=float32)
